# Generated by Django 5.0.6 on 2026-06-28 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام مزرعه")),
                (
                    "farm_type",
                    models.CharField(
                        choices=[
                            ("broiler", "مرغداری گوشتی"),
                            ("breeder", "مرغداری مادری"),
                            ("layer", "مرغداری تخم\u200cگذار"),
                        ],
                        max_length=20,
                        verbose_name="نوع مزرعه",
                    ),
                ),
                ("capacity", models.IntegerField(verbose_name="ظرفیت (قطعه)")),
                (
                    "location",
                    models.CharField(blank=True, max_length=300, verbose_name="موقعیت"),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس دقیق")),
                (
                    "reminder_interval_days",
                    models.IntegerField(default=7, verbose_name="فاصله یادآوری (روز)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "مزرعه",
                "verbose_name_plural": "مزارع",
                "ordering": ["-created_at"],
            },
        ),
    ]
