# Generated by Django 5.0.6 on 2026-06-28 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("farms", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("week1", "هفته اول"),
                            ("periodic", "دوره\u200cای"),
                            ("end_cycle", "پایان دوره"),
                            ("complaint", "شکایت"),
                            ("general", "عمومی"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="نوع بازخورد",
                    ),
                ),
                (
                    "satisfaction",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="رضایت (۱-۵)",
                    ),
                ),
                (
                    "has_complaint",
                    models.BooleanField(default=False, verbose_name="شکایت دارد"),
                ),
                (
                    "complaint_text",
                    models.TextField(blank=True, verbose_name="متن شکایت"),
                ),
                (
                    "mortality_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="نرخ تلفات (%)",
                    ),
                ),
                (
                    "production_note",
                    models.TextField(blank=True, verbose_name="یادداشت تولید"),
                ),
                (
                    "will_repurchase",
                    models.CharField(
                        choices=[
                            ("yes", "بله"),
                            ("maybe", "شاید"),
                            ("no", "خیر"),
                            ("unknown", "مشخص نیست"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="قصد خرید مجدد",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="farms.farm",
                        verbose_name="مزرعه",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="sales.sale",
                        verbose_name="فروش مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازخورد",
                "verbose_name_plural": "بازخوردها",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
