# Generated by Django 5.0.6 on 2026-06-28 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("discount", "تخفیف قیمت"),
                            ("payment_terms", "شرایط بهتر پرداخت"),
                            ("priority_supply", "اولویت عرضه"),
                            ("quality_guarantee", "تضمین کیفیت"),
                            ("replacement_guarantee", "تضمین جایگزینی"),
                            ("custom", "سفارشی"),
                        ],
                        max_length=30,
                        verbose_name="نوع پیشنهاد",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="عنوان پیشنهاد"),
                ),
                ("details", models.TextField(verbose_name="جزئیات")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("sent", "ارسال شده"),
                            ("accepted", "پذیرفته شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ ارسال"
                    ),
                ),
                (
                    "response_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پاسخ"
                    ),
                ),
                (
                    "customer_response",
                    models.TextField(blank=True, verbose_name="پاسخ مشتری"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیشنهاد حفظ مشتری",
                "verbose_name_plural": "پیشنهادات حفظ مشتری",
                "ordering": ["-created_at"],
            },
        ),
    ]
