# Generated by Django 5.0.6 on 2026-06-28 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurnAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "کم\u200cریسک"),
                            ("medium", "ریسک متوسط"),
                            ("high", "پرریسک"),
                        ],
                        max_length=10,
                        verbose_name="سطح ریسک",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(default=0, verbose_name="امتیاز ریسک (۰-۱۰۰)"),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("sale_created", "ثبت فروش"),
                            ("feedback_low", "بازخورد منفی"),
                            ("no_response", "عدم پاسخ"),
                            ("complaint", "شکایت"),
                            ("purchase_drop", "کاهش خرید"),
                            ("payment_delay", "تأخیر پرداخت"),
                            ("manual", "دستی"),
                            ("end_cycle", "پایان دوره"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="علت بررسی",
                    ),
                ),
                (
                    "satisfaction_score",
                    models.IntegerField(blank=True, null=True, verbose_name="رضایت"),
                ),
                (
                    "has_complaint",
                    models.BooleanField(default=False, verbose_name="شکایت دارد"),
                ),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("responsive", "پاسخ\u200cگو"),
                            ("delayed", "تأخیر"),
                            ("no_response", "بی\u200cپاسخ"),
                        ],
                        default="responsive",
                        max_length=20,
                        verbose_name="وضعیت پاسخ",
                    ),
                ),
                (
                    "purchase_trend",
                    models.CharField(
                        choices=[
                            ("up", "صعودی"),
                            ("stable", "ثابت"),
                            ("down", "نزولی"),
                        ],
                        default="stable",
                        max_length=10,
                        verbose_name="روند خرید",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ارزیاب",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churn_assessments",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارزیابی ریسک",
                "verbose_name_plural": "ارزیابی\u200cهای ریسک",
                "ordering": ["-assessed_at"],
            },
        ),
    ]
