# Generated by Django 5.0.6 on 2026-06-28 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام")),
                ("phone", models.CharField(max_length=20, verbose_name="تلفن")),
                (
                    "phone2",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="تلفن دوم"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="شهر")),
                (
                    "province",
                    models.CharField(blank=True, max_length=100, verbose_name="استان"),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "کم\u200cریسک"),
                            ("medium", "ریسک متوسط"),
                            ("high", "پرریسک"),
                        ],
                        default="low",
                        max_length=10,
                        verbose_name="سطح ریسک",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کارشناس فروش",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشتری",
                "verbose_name_plural": "مشتریان",
                "ordering": ["-created_at"],
            },
        ),
    ]
