# Generated by Django 5.0.6 on 2026-06-28 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("farms", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("feedback", "بازخورد"),
                            ("purchase", "یادآور خرید"),
                            ("followup", "پیگیری"),
                            ("churn_alert", "هشدار ریسک"),
                        ],
                        max_length=20,
                        verbose_name="نوع یادآور",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="تاریخ سررسید")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "انجام نشده"),
                            ("done", "انجام شد"),
                            ("overdue", "عقب\u200cافتاده"),
                            ("urgent", "نیاز به پیگیری فوری"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ انجام"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مسئول",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="farms.farm",
                        verbose_name="مزرعه",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="sales.sale",
                        verbose_name="فروش مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادآور",
                "verbose_name_plural": "یادآورها",
                "ordering": ["due_date", "status"],
            },
        ),
    ]
