# Generated by Django 5.0.6 on 2026-06-28 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateField(verbose_name="تاریخ فروش")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="مقدار (کیلوگرم)"
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="قیمت واحد (تومان)",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="مبلغ کل (تومان)"
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نوع محصول"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "پرداخت شده"),
                            ("partial", "پرداخت جزئی"),
                            ("pending", "معلق"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت پرداخت",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="farms.farm",
                        verbose_name="مزرعه",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "فروش",
                "verbose_name_plural": "فروش\u200cها",
                "ordering": ["-sale_date"],
            },
        ),
    ]
